// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc1939.KillerRabbit.subsystems;
import org.usfirst.frc1939.KillerRabbit.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Shooter extends Subsystem {
    
    public static final double spinDelay = 3;
    
    private static final double forwardSpeed = -0.9;
    private static final double backSpeed = -0.7;
    
    private boolean spinning;
    private boolean forward;
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController front = RobotMap.shooterFront;
    SpeedController back = RobotMap.shooterBack;
    DoubleSolenoid piston = RobotMap.shooterPiston;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
        
        this.stopWheels();
        this.pistonBack();
    }
    
    public boolean isSpinning(){
        return spinning;
    }
    
    public boolean isForward(){
        return forward;
    }
    
    public void pistonForward(){
        forward = true;
        piston.set(DoubleSolenoid.Value.kForward);
    }
    
    public void pistonBack(){
        forward = false;
        piston.set(DoubleSolenoid.Value.kReverse);
    }
    
    public void spinWheels(){
        spinning = true;
        front.set(forwardSpeed);
        back.set(backSpeed);
    }
    
    public void stopWheels(){
        spinning = false;
        front.set(0);
        back.set(0);
    }
    
}
