// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc1939.KillerRabbit.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc1939.KillerRabbit.Robot;
/**
 *
 */
public class  DriveWithJoystick extends Command {
    public DriveWithJoystick() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drivetrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        double x = Robot.oi.leftStick.getX();
        double y = Robot.oi.leftStick.getY();
        double z = Robot.oi.rightStick.getX();
        if(Math.abs(x)<0.02) x = 0;
        if(Math.abs(y)<0.02) y = 0;
        if(Math.abs(z)<0.02) z = 0;
        
        double multiplier = 0.0;
        if(Robot.oi.turboButton.get()){
            multiplier = 0.3;
        }else{
            multiplier = 1.0;
        }
        Robot.drivetrain.drive(x,y, z, multiplier, 0);
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }
    // Called once after isFinished returns true
    protected void end() {
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
